#ifndef COINBILL_USER_TRANSACTION_V1
#define COINBILL_USER_TRANSACTION_V1

namespace CoinBill {
    enum CB_TransactionType {
		ACCOUNT_REGISTER							= 0x01,
        ACCOUNT_SEND_BALANCE						= 0x02,
        ACCOUNT_INIT_BALANCE						= 0x03,
		ACCOUNT_SET_INFO							= 0x04,
		ACCOUNT_SET_SHORT_NAME						= 0x05,
		ACCOUNT_NODIFY_WARNING						= 0x06,
		ACCOUNT_BAN									= 0x07,
		ACCOUNT_UNBAN								= 0x08,
		ACCOUNT_AGREE_ON_ADMIN						= 0x09,

		TRANSACTION_BLOCK_PROOF						= 0x11,
		TRANSACTION_PROOF							= 0x12,
		TRANSACTION_REQ_DISCARD						= 0x13,

		CONTRACT_CREATE								= 0x21,
		CONTRACT_DISCARD							= 0x22,
		CONTRACT_GIVE_OWNSHIP						= 0x23,
		CONTRACT_DO_EXECUTE							= 0x24,

		BLOCK_CREATION_NODIFY_POW					= 0xAE,
		BLOCK_CREATION_NODIFY_POS					= 0xAF,

		ADMIN_AGREE_AND_ACCEPT						= 0xD0,
		ADMIN_CREATE_NEW							= 0xD1,

		ADMIN_FORCE_BAN								= 0xE0,
		ADMIN_FORCE_UNBAN							= 0xE1,
		ADMIN_FORCE_GIVE_COIN						= 0xE2,
		ADMIN_FORCE_TAKE_COIN						= 0xE3,
		ADMIN_FORCE_SET_BLOCK_POS					= 0xE4,
		ADMIN_FORCE_SET_NEXT_BLOCK					= 0xE5,
		ADMIN_FORCE_STOP_TRANSACTIONS				= 0xE6,
		ADMIN_FORCE_STOP_BLOCK_CREATION				= 0xE7,

		ADMIN_BAN									= 0xF0,
		ADMIN_UNBAN									= 0xF1,
		ADMIN_GIVE_COIN								= 0xF2,
		ADMIN_TAKE_COIN								= 0xF3,
		ADMIN_SET_BLOCK_POS							= 0xF4,
		ADMIN_SET_NEXT_BLOCK						= 0xF5,
		ADMIN_STOP_TRANSACTIONS						= 0xF6,
		ADMIN_STOP_BLOCK_CREATION					= 0xF7
    };

    class CB_Transaction {
		CB_TransactionType Kind;
    };
}

#endif